### ISSUE TITLE
How to add space between rating objects?

### ISSUE THREAD

**Issue by hagile** [glenyi/TPFloatRatingView#1]
Suppose, I'm using using "star" image for the rating, is there a way that I can add space between each star? Of course, current work is just too good. But I need to have some space in between. Thanks!

**Comment by JayMehta711** [comment]
@hagile Hi Babla Bhai ,
you can add space in this method manually.
Check this method "layoutSubviews" 
Happy Coding....

**Comment by hagile** [comment]
@JayMehta711 , babla, thanks baka ! :+1:
